### ISSUE TITLE
google drive link not working

### ISSUE THREAD

**Issue by arjunskumar** [ethz-asl/kalibr#310]
Unable to access google drive files

**Comment by rg9127** [comment]
I was able to download the CDE package you could try following,
**Method 1:** 
1). click on the download link and wait for it, takes about 4 mins.

**Method 2:**
1). Open the link, instead of downloading it, add it to your drive.
2). Go to your drive and download the package, takes some time again.

Let me know if any of the above worked.

**Comment by arjunskumar** [comment]
@rg9127 Thanks, it worked
