### ISSUE TITLE
calibration target  file in PDF format

### ISSUE THREAD

**Issue by hahahaHusky** [ethz-asl/kalibr#333]
Hi !
I try to generate the calibration board .When I run the command line ,
          **kalibr_create_target_pdf --type apriltag --nx 6 --ny 6 --tsize 0.088 --tspace 0.3**
the reply is , command not found .
Who can  give me a calibration target  file in **PDF format** ?
Thank you very much !

**Comment by kannidekan** [comment]
execuse me, do you know how could i get the IMU YAML file of the requirements in the camera-imu calibration? #341 

Thanks very much!

**Comment by goldbattle** [comment]
Please try on the latest master since building has been fixed. Make sure to source your ROS workspace.

**Comment by YonatanSimson** [comment]
Try this link: https://drive.google.com/file/d/1DqKWgePodCpAKJCd_Bz-hfiEQOSnn_k0/view?usp=sharing

**Comment by Hezhexi2002** [comment]
> Please try on the latest master since building has been fixed. Make sure to source your ROS workspace.

Hi,I use the [Dockerfile_ros1_20_04](https://github.com/ethz-asl/kalibr/blob/master/Dockerfile_ros1_20_04) to install kalibr and also get this error too:
![image](https://user-images.githubusercontent.com/53631206/215966455-adfd34b4-68d0-4a22-98a5-eef5250410e9.png)
so is this means I have to build the kalibr from source in order to run the `kalibr_create_target_pdf` command？

**Comment by 987428377** [comment]
You can use the following command:  
rosrun kalibr kalibr_create_target_pdf --type apriltag --nx 12 --ny 12 --tsize 0.088 --tspace 0.3
