### ISSUE TITLE
what is the purpose of imu noise density bias random walk for ?

### ISSUE THREAD

**Issue by Ashing00** [ethz-asl/kalibr#440]
Hi,

may I know what is the purpose of imu noise density bias random walk for ?
and this configuration ( imu.yaml) be used once or everytime I need to re-create it for different camera? 

 for Camera-IMU calibration ,do we need to do IMU calibration ready firstly,right?

**Comment by gotiobg** [comment]
Noise density and ARW (Angular Random Walk) are used to calibrate the IMU.
The values can be used every time if you had already calibrated them for a long enough time, say two hours.

You can check https://github.com/gaowenliang/imu_utils as it gives you these needed params in order to use kalibr.
Here is a nice guide for MPU6050 https://automaticaddison.com/visualize-imu-data-using-the-mpu6050-ros-and-jetson-nano/

**Comment by Ashing00** [comment]
hi gotiobg 
got it ,thank you

**Comment by gotiobg** [comment]
You're welcome.
