### ISSUE TITLE
Understanding IMU Calibration and Allan Variance calculation

### ISSUE THREAD

**Issue by RajS999** [ethz-asl/kalibr#663]
I was referring to calculation of gyro and accel white noise and random walk using the video [Visual-Inertial Sensor Calibration - A Complete Tutorial and Discussion](https://www.youtube.com/watch?v=BtzmsuJemgI) for my Intel Realsense. I have following doubts:

1. At timestamp [25:48](https://youtu.be/BtzmsuJemgI?si=72q7A4N5AyiuZnVz&t=1548), video says, typically we dont use values generated by Allan Variance ROS directly and we inflate them by order of 10 times, may be by 20. Why is it so?
2. I read we can obtain Angle Random Walk, Bias Instability, and Rate Random Walk from Allan Variance plot by reading Allan Variance value at `T=1, Slope=0, T=3` respectively. Why exactly Angle Random Walk is read at T=1 and Rate Random Walk at T=3 and not at some other values? Is it that these types of noise are **"empirically observed"** to most dominant in Allan Variance plot at these cluster interval values?
3. How often and when we have to calibrate IMU and calculate gyro and accel white noise and random walk (if we are flying drone in different temperature environment)? Do we have to calculate gyro and accel white noise and random walk every time we calibrate the IMU?

**Comment by goldbattle** [comment]
There are additional sources of noises not captured by the calibration procedure, in the ideal case we wouldn't need any inflation. Noise caused by temp / humidity / motors of the robot etc will all have an impact here.

I would read the original specification if you need to see how they determined the method:
[[IEEE Standard Specification Format Guide and Test Procedure for Single-Axis Interferometric Fiber Optic Gyros](https://ieeexplore.ieee.org/document/660628/) (page 71, section C)]

It ends up being this chart here:
![image](https://github.com/ethz-asl/kalibr/assets/2222562/3642d9fb-fb64-498b-8b23-e40f6a9acdac)

It should be a onetime process, but if you take the drone to a very hot (or cold) or completely different environment, then I would expect all sensors to need to be re-calibrated in this case.
